EMS/EMS/Controllers/EmployeeAddressController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EMS.Models;

namespace EMS.Controllers
{
    public class EmployeeAddressController : Controller
    {
        private ModelEMS db = new ModelEMS();

        // GET: EmployeeAddress
        public ActionResult Index()
        {
            var tbl_EmployeeAddress = db.tbl_EmployeeAddress.Include(t => t.tbl_city_master).Include(t => t.tbl_country_master).Include(t => t.tbl_Employee).Include(t => t.tbl_state_master);
            return View(tbl_EmployeeAddress.ToList());
        }

        // GET: EmployeeAddress/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_EmployeeAddress tbl_EmployeeAddress = db.tbl_EmployeeAddress.Find(id);
            if (tbl_EmployeeAddress == null)
            {
                return HttpNotFound();
            }
            return View(tbl_EmployeeAddress);
        }

        // GET: EmployeeAddress/Create
        public ActionResult Create()
        {
            ViewBag.city = new SelectList(db.tbl_city_master, "id", "code");
            ViewBag.country = new SelectList(db.tbl_country_master, "id", "code");
            ViewBag.employee_id = new SelectList(db.tbl_Employee, "id", "empno");
            ViewBag.state = new SelectList(db.tbl_state_master, "id", "code");
            return View();
        }

        // POST: EmployeeAddress/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,employee_id,ispermanant,addressline1,addressline2,country,state,city,pin,contact,status")] tbl_EmployeeAddress tbl_EmployeeAddress)
        {
            if (ModelState.IsValid)
            {
                db.tbl_EmployeeAddress.Add(tbl_EmployeeAddress);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.city = new SelectList(db.tbl_city_master, "id", "code", tbl_EmployeeAddress.city);
            ViewBag.country = new SelectList(db.tbl_country_master, "id", "code", tbl_EmployeeAddress.country);
            ViewBag.employee_id = new SelectList(db.tbl_Employee, "id", "empno", tbl_EmployeeAddress.employee_id);
            ViewBag.state = new SelectList(db.tbl_state_master, "id", "code", tbl_EmployeeAddress.state);
            return View(tbl_EmployeeAddress);
        }

        // GET: EmployeeAddress/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_EmployeeAddress tbl_EmployeeAddress = db.tbl_EmployeeAddress.Find(id);
            if (tbl_EmployeeAddress == null)
            {
                return HttpNotFound();
            }
            ViewBag.city = new SelectList(db.tbl_city_master, "id", "code", tbl_EmployeeAddress.city);
            ViewBag.country = new SelectList(db.tbl_country_master, "id", "code", tbl_EmployeeAddress.country);
            ViewBag.employee_id = new SelectList(db.tbl_Employee, "id", "empno", tbl_EmployeeAddress.employee_id);
            ViewBag.state = new SelectList(db.tbl_state_master, "id", "code", tbl_EmployeeAddress.state);
            return View(tbl_EmployeeAddress);
        }

        // POST: EmployeeAddress/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,employee_id,ispermanant,addressline1,addressline2,country,state,city,pin,contact,status")] tbl_EmployeeAddress tbl_EmployeeAddress)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_EmployeeAddress).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.city = new SelectList(db.tbl_city_master, "id", "code", tbl_EmployeeAddress.city);
            ViewBag.country = new SelectList(db.tbl_country_master, "id", "code", tbl_EmployeeAddress.country);
            ViewBag.employee_id = new SelectList(db.tbl_Employee, "id", "empno", tbl_EmployeeAddress.employee_id);
            ViewBag.state = new SelectList(db.tbl_state_master, "id", "code", tbl_EmployeeAddress.state);
            return View(tbl_EmployeeAddress);
        }

        // GET: EmployeeAddress/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_EmployeeAddress tbl_EmployeeAddress = db.tbl_EmployeeAddress.Find(id);
            if (tbl_EmployeeAddress == null)
            {
                return HttpNotFound();
            }
            return View(tbl_EmployeeAddress);
        }

        // POST: EmployeeAddress/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_EmployeeAddress tbl_EmployeeAddress = db.tbl_EmployeeAddress.Find(id);
            db.tbl_EmployeeAddress.Remove(tbl_EmployeeAddress);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EMS/EMS/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EMS.Models;

namespace EMS.Controllers
{
    public class EmployeeController : Controller
    {
        private ModelEMS db = new ModelEMS();

        // GET: Employee
        public ActionResult Index()
        {
            return View(db.tbl_Employee.ToList());
        }

        // GET: Employee/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Employee tbl_Employee = db.tbl_Employee.Find(id);
            if (tbl_Employee == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Employee);
        }

        // GET: Employee/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Employee/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,empno,name,dept,contact,email,status")] tbl_Employee tbl_Employee)
        {
            if (ModelState.IsValid)
            {
                db.tbl_Employee.Add(tbl_Employee);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_Employee);
        }

        // GET: Employee/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Employee tbl_Employee = db.tbl_Employee.Find(id);
            if (tbl_Employee == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Employee);
        }

        // POST: Employee/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,empno,name,dept,contact,email,status")] tbl_Employee tbl_Employee)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Employee).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_Employee);
        }

        // GET: Employee/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Employee tbl_Employee = db.tbl_Employee.Find(id);
            if (tbl_Employee == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Employee);
        }

        // POST: Employee/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_Employee tbl_Employee = db.tbl_Employee.Find(id);
            db.tbl_Employee.Remove(tbl_Employee);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EMS/EMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Employee Management System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Employee Management System", "Index", "Employee", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Employees", "Index", "Employee")</li>
                    <li>@Html.ActionLink("Employee Addresses", "Index", "EmployeeAddress")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script>
        window.onbeforeunload = function () {
            $("input[type=button], input[type=submit]").attr("disabled", "disabled");

        };
        function bindDropDown(url, controlid, postData, value) {
            $.ajax({
                cache: false,
                type: "POST",
                url: url,
                data: postData,
                dataType: "json",
                traditional: true,
                success: function (data) {
                    var ddl = $("#" + controlid + "");
                    ddl.html('');
                    ddl.append($('<option></option>').val(0).html("--Select--"));
                    $.each(data, function (id, option) {
                        ddl.append($('<option></option>').val(option.Value).html(option.Text));
                    });
                    if (value != null && value != "")
                        $("#" + controlid + "").val(value);
                    else $("#" + controlid + "").val(0);
                },
                error: function (xhr, ajaxOptions, thrownError) {
                    console.log(ajaxOptions + 'Failed to retrieve states.');
                }
            });
        }

    </script>
    @RenderSection("scripts", required: false)
</body>
</html>